<Project Sdk="Microsoft.NET.Sdk" InitialTargets="GenerateCustomPropsFile">
	<Import Project="GamePath.props" Condition="Exists('GamePath.props')" />

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <TargetFramework>net481</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>ModMenu_RT</AssemblyName>
    <RootNamespace>ModMenu</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <Nullable>enable</Nullable>
    <RogueTraderData>$(LocalAppData)Low\Owlcat Games\Warhammer 40000 Rogue Trader</RogueTraderData>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\**" />
    <Compile Remove="lib\**" />
    <EmbeddedResource Remove="Assets\**" />
    <EmbeddedResource Remove="lib\**" />
    <None Remove="Assets\**" />
    <None Remove="lib\**" />
    <None Remove="GamePath.props" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <None Remove="WittleWolfie.png" />
	  <None Remove="UI_CharGen_IconDislike.png" />
	  <None Remove="UI_CharGen_IconLike.png" />
	  <None Remove="UI_journal_iconok_new2.png" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="NewTypes\ModRecording\Icons\UI_CharGen_IconDislike.png" />
    <None Remove="NewTypes\ModRecording\Icons\UI_CharGen_IconLike.png" />
    <None Remove="NewTypes\ModRecording\Icons\UI_journal_iconok_new2.png" />
    <None Remove="NewTypes\ModRecording\Icons\UI_QuestNotification_IconFail.png" />
    <None Remove="NewTypes\ModRecording\Icons\UI_QuestNotification_IconNew.png" />
    <None Remove="NewTypes\ModRecording\Icons\UI_QuestNotification_IconOk.png" />
    <None Remove="TestSettingsIllustration.png" />
    <None Remove="TestSettingsIllustration2.png" />
    <None Remove="UI_QuestNotification_IconFail.png" />
  </ItemGroup>


  <ItemGroup>
	  <EmbeddedResource Include="NewTypes\ModRecording\Icons\UI_CharGen_IconDislike.png" />
	  <EmbeddedResource Include="NewTypes\ModRecording\Icons\UI_CharGen_IconLike.png" />
	  <EmbeddedResource Include="NewTypes\ModRecording\Icons\UI_journal_iconok_new2.png" />
	  <EmbeddedResource Include="NewTypes\ModRecording\Icons\UI_QuestNotification_IconFail.png" />
	  <EmbeddedResource Include="NewTypes\ModRecording\Icons\UI_QuestNotification_IconNew.png" />
	  <EmbeddedResource Include="NewTypes\ModRecording\Icons\UI_QuestNotification_IconOk.png" />
	  <EmbeddedResource Include="TestSettingsIllustration.png" />
	  <EmbeddedResource Include="TestSettingsIllustration2.png" />
	  <EmbeddedResource Include="WittleWolfie.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.AssemblyPublicizer.MSBuild" Version="0.4.3" IncludeAssets="compile; build; contentfiles; analyzers; buildtransitive" PrivateAssets="all" />
    <PackageReference Include="MicroUtils.HarmonyAnalyzers" Version="1.6.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.IO.Compression" />
    <Reference Include="$(RogueTraderData)\UnityModManager\UnityModManager.dll*" Private="false" Publicize="true" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Code.dll*" Private="false" Publicize="true" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\RogueTrader.*.dll*" Private="false" Publicize="true" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Owlcat.*.dll*" Private="false" Publicize="true" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Kingmaker.*.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Utility.*.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Assembly-CSharp-firstpass.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\LocalizationShared.dll" Private="false" />
	  <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Unity.TextMeshPro.dll*" Private="false" Publicize="true" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\UnityEngine.CoreModule.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\UnityEngine.ImageConversionModule.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\UnityEngine.TextRenderingModule.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\UnityEngine.UI.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\UnityEngine.UIModule.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\UniRx.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Newtonsoft.Json.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\Rewired_Core.dll" Private="false" />
    <Reference Include="$(RogueTraderInstallDir)\WH40KRT_Data\Managed\0Harmony.dll" Private="false" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Info.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="Deploy" AfterTargets="Build">
  <!--<Target Name="Deploy">-->
    <ItemGroup>
      <ToCopy Include="$(OutputPath)\$(AssemblyName).dll" />
	    <ToCopy Include="$(OutputPath)\$(AssemblyName).pdb" />
	    <ToCopy Include="$(OutputPath)\Info.json" />
    </ItemGroup>

    <Copy SourceFiles="@(ToCopy)" DestinationFolder="$(RogueTraderData)\UnityModManager\$(MSBuildProjectName)" />
  </Target>

  <!--<Target Name="PublishToSteamWorkshop" AfterTargets="Publish">
    <PublishToWorkshop PathToManifest="$(MSBuildThisFileDirectory)\ModDetails\OwlcatModificationManifest.json" ImageDir="$(MSBuildThisFileDirectory)\ModDetails\" BuildDir="$(SolutionDir)$(OutDir)" GameAppId="2186680" PathToDescription="$(MSBuildThisFileDirectory)\ModDetails\description" />
  </Target>-->

  <Target Name="GenerateCustomPropsFile" Condition="$(RogueTraderInstallDir) == ''">
    <Exec Command="findstr /C:&quot;Mono path[0]&quot; &quot;$(RogueTraderData)\Player.log&quot;" IgnoreExitCode="true" ConsoleToMSBuild="true">
      <Output TaskParameter="ExitCode" PropertyName="ExitCode" />
      <Output TaskParameter="ConsoleOutput" PropertyName="MonoPathLine" />
    </Exec>

    <PropertyGroup>
      <MonoPathRegex>^Mono path\[0\] = '(.*?)/WH40KRT_Data/Managed'$</MonoPathRegex>
    </PropertyGroup>

    <PropertyGroup>
      <RogueTraderInstallDir>$([System.Text.RegularExpressions.Regex]::Match($(MonoPathLine), $(MonoPathRegex)).Groups[1].Value)</RogueTraderInstallDir>
    </PropertyGroup>

    <WriteLinesToFile File="GamePath.props" Lines="&lt;Project xmlns='http://schemas.microsoft.com/developer/msbuild/2003'&gt; &#xD;&#xA;	&lt;PropertyGroup&gt; &#xD;&#xA;		&lt;RogueTraderInstallDir&gt;$(RogueTraderInstallDir)&lt;/RogueTraderInstallDir&gt;&#xD;&#xA;	&lt;/PropertyGroup&gt;&#xD;&#xA;&lt;/Project&gt;" Overwrite="true" Encoding="utf-8" />
  </Target>

</Project>
